"use client";
import {useState} from "react";
import {Button} from "@/components/silicon-ui/button/button";
import {Input} from "@/components/silicon-ui/input/input";
import {Textarea} from "@/components/silicon-ui/textarea/textarea";
import {Select} from "@/components/silicon-ui/select/select";
import {Switch} from "@/components/silicon-ui/switch/switch";
import {ConfirmMorph} from "@/components/silicon-ui/confirm-morph/confirm-morph";
import {Page,PageHeader,Section,Surface} from "@/components/foundation/layout/layout";
import {Empty,Feedback,ResourceError,Who,enc,label,mutate,todoStatuses,useAction,useResource} from "./common";
import type {Actor,Todo,Me,Rule,EmailSettings,NotificationSettings,Subscription} from "./types";
import s from "./product.module.css";
export function Notifications(){const me=useResource<Me>("/v1/me");const email=useResource<EmailSettings>("/v1/email-settings");const [silicon,setSilicon]=useState("");const selected=silicon||me.data?.silicons[0]?.id;return <Page width="reading"><PageHeader title="Notifications" description="Choose which progress reaches your inbox and your Silicons."/><ResourceError error={me.error}/><Section title="Email updates" description="Project completion is enabled by default for the email you shared with Commit."><ResourceError error={email.error}/>{email.data?<EmailForm initial={email.data}/>:null}</Section><Section title="Silicon delivery" description="Deliver todo events to an HTTPS endpoint on behalf of one of your Silicons.">{me.data?.silicons.length?<Select label="Silicon" value={selected} onValueChange={setSilicon} options={me.data.silicons.map(a=>({value:a.id,label:a.id}))}/>:null}{selected?<SiliconNotifications key={selected} silicon={selected}/>:<Empty>Your Silicons appear here after they use Commit. Their notification settings remain available through the command line.</Empty>}</Section></Page>;}
function EmailForm({initial}:{initial:EmailSettings}){const [value,setValue]=useState(initial);const a=useAction();return <Surface><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(()=>mutate("/v1/email-settings","PUT",{email:value.email,enabled:value.enabled,project_completed:value.project_completed,project_updates:value.project_updates,task_completed:value.task_completed,task_assigned:value.task_assigned}),"Email settings saved");}}><Input label="Email address" type="email" value={value.email} onChange={e=>setValue({...value,email:e.target.value})}/>{(["enabled","project_completed","project_updates","task_completed","task_assigned"] as const).map(key=><Switch key={key} label={key==="enabled"?"Email delivery":label(key)} checked={value[key]} onCheckedChange={checked=>setValue({...value,[key]:checked})}/>)}<Feedback action={a}/><Button type="submit" disabled={a.busy}>Save email settings</Button></form></Surface>;}
function RuleForm({initial,onChange}:{initial:Rule|null;onChange:(rule:Rule|null)=>void}){const [rule,setRule]=useState<Rule|null>(initial);const change=(next:Rule|null)=>{setRule(next);onChange(next);};return <div className={s.form}><Select label="Events to deliver" value={rule?.scope??"none"} onValueChange={scope=>change(scope==="none"?null:{scope:scope as Rule["scope"],...(scope==="specific_statuses"?{statuses:["completed"]}:{})})} options={[{value:"none",label:"No subscription"},{value:"any_update",label:"Every update"},{value:"status_updates",label:"Status changes"},{value:"specific_statuses",label:"Selected statuses"}]}/>{rule?.scope==="specific_statuses"?todoStatuses.map(status=><Switch key={status} label={label(status)} checked={rule.statuses?.includes(status)??false} onCheckedChange={checked=>change({...rule,statuses:checked?[...rule.statuses??[],status]:(rule.statuses??[]).filter(s=>s!==status)})}/>):null}</div>;}
function SiliconNotifications({silicon}:{silicon:string}){const path=`/v1/notification-settings?silicon=${enc(silicon)}`;const data=useResource<NotificationSettings>(path);const action=useAction();return <><ResourceError error={data.error}/>{data.data?<NotificationForm key={JSON.stringify(data.data)} path={path} initial={data.data} action={action}/>:null}<Feedback action={action}/></>;}
function NotificationForm({path,initial,action:a}:{path:string;initial:NotificationSettings;action:ReturnType<typeof useAction>}){const [url,setUrl]=useState(initial.webhook_url??"");const [rule,setRule]=useState(initial.todo_list_subscription);return <Surface><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(()=>mutate(path,"PUT",{webhook_url:url.trim()||null,todo_list_subscription:rule},initial.version),"Silicon notification settings saved");}}><Input label="Webhook URL" type="url" description="An HTTPS endpoint that accepts Commit todo events." value={url} onChange={e=>setUrl(e.target.value)}/><RuleForm initial={rule} onChange={setRule}/><Button type="submit" disabled={a.busy}>Save Silicon settings</Button></form></Surface>;}
export function TodoSubscription({todo}:{todo:Todo}){const me=useResource<Me>("/v1/me");const owner=todo.assigned_by;const eligible=owner.type==="silicon"&&owner.uuid!==todo.assigned_to.uuid&&me.data?.silicons.some(a=>a.uuid===owner.uuid);return <Section title="Todo notifications" description="The Silicon that delegated a todo can subscribe to its progress.">{eligible?<><Who actor={owner}/><SubscriptionResource todoId={todo.id}/></>:<p className={s.muted}>Per-todo subscriptions are available when a Silicon you manage delegated this todo to another account. Email preferences are in Notifications.</p>}</Section>;}
function SubscriptionResource({todoId}:{todoId:string}){const path=`/v1/todos/${todoId}/notification-subscription`;const data=useResource<Subscription>(path);const action=useAction();return <><ResourceError error={data.error}/>{data.data?<SubscriptionForm key={JSON.stringify(data.data)} path={path} initial={data.data} action={action}/>:null}<Feedback action={action}/></>;}
function SubscriptionForm({path,initial,action:a}:{path:string;initial:Subscription;action:ReturnType<typeof useAction>}){const [rule,setRule]=useState(initial.subscription);return <Surface><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(()=>mutate(path,"PUT",{subscription:rule},initial.version),"Todo subscription saved");}}><RuleForm initial={rule} onChange={setRule}/><Button type="submit" disabled={a.busy}>Save todo subscription</Button></form></Surface>;}
export function Silicons(){const me=useResource<Me>("/v1/me");const [selected,setSelected]=useState("");const silicon=selected||me.data?.silicons[0]?.id;return <Page width="reading"><PageHeader title="Your Silicons" description="Manage which accounts may assign work to your Silicons."/><ResourceError error={me.error}/>{me.data?.silicons.length?<><Select label="Silicon" value={silicon} onValueChange={setSelected} options={me.data.silicons.map(a=>({value:a.id,label:a.id}))}/>{silicon?<Allowlist key={silicon} silicon={silicon}/>:null}</>:<Surface><Empty>Your Silicons appear after they use Commit. Your custodian relationship comes from Silicon Accounts.</Empty></Surface>}</Page>;}
function Allowlist({silicon}:{silicon:string}){const path=`/v1/silicons/${enc(silicon)}/allowed-accounts`;const data=useResource<{silicon:Actor;allowed_accounts:{account:Actor}[]|Actor[];allowed?:{account:Actor}[]}>(path);const [account,setAccount]=useState("");const a=useAction();const entries=data.data?.allowed_accounts??data.data?.allowed??[];return <Section title="Allowed accounts" description="The custodian and Silicons with the same custodian already have access. Allow others by their exact c: or si: id."><ResourceError error={data.error}/><Surface><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(async()=>{await mutate(`${path}/${enc(account.trim())}`,"PUT",{});setAccount("");},"Account allowed");}}><Input label="Account to allow" required value={account} placeholder="c:ada or si:scout" onChange={e=>setAccount(e.target.value)}/><Button type="submit" disabled={a.busy}>Allow account</Button><Feedback action={a}/></form>{entries.map(entry=>{const actor="account" in entry?entry.account:entry;return <div className={`${s.item} ${s.spread}`} key={actor.uuid}><Who actor={actor}/><ConfirmMorph label={`Remove ${actor.id}`} onConfirm={async()=>{if(!await a.run(()=>mutate(`${path}/${enc(actor.id)}`,"DELETE"),"Account removed"))throw new Error("Could not remove account");}}/></div>;})}</Surface></Section>;}
export function Report(){const [message,setMessage]=useState(""),[pr,setPr]=useState("");const a=useAction();return <Page width="narrow"><PageHeader title="Report a problem" description="Tell the Commit maintainers what happened and how to reproduce it."/><Surface><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(async()=>{await mutate("/v1/reports","POST",{message,pr:pr||null});setMessage("");setPr("");},"Report queued for the Commit maintainers");}}><Textarea label="What happened?" required rows={8} maxLength={20000} value={message} onChange={e=>setMessage(e.target.value)}/><Input label="Related Commit pull request" type="url" description="Optional." value={pr} onChange={e=>setPr(e.target.value)}/><Feedback action={a}/><Button type="submit" disabled={a.busy}>Send report</Button></form></Surface></Page>;}
