"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Button} from "@/components/arc/button/button";
import {Input} from "@/components/arc/input/input";
import {Textarea} from "@/components/arc/textarea/textarea";
import {Select} from "@/components/arc/select/select";
import {ConfirmMorph} from "@/components/arc/confirm-morph/confirm-morph";
import {Page,PageHeader,Section,Surface} from "@/components/foundation/layout/layout";
import {queryString} from "@/lib/client/api";
import {Attachments,Empty,Feedback,Modal,More,ResourceError,Status,StatusSelect,Who,enc,lines,mutate,stamp,useAction,useList,useResource} from "./common";
import {TodoSubscription} from "./notifications";
import type {Todo,Note,Me,Project,PageResult} from "./types";
import s from "./product.module.css";
export function TodoForm({todo,close,saved}:{todo?:Todo;close:()=>void;saved:(todo:Todo)=>void}){
 const me=useResource<Me>("/v1/me");const projects=useList<Project>("/v1/projects?limit=100");const a=useAction();
 const [title,setTitle]=useState(todo?.title??"");const [description,setDescription]=useState(todo?.description??"");const [assigned,setAssigned]=useState(todo?.assigned_to.id??"");const [status,setStatus]=useState(todo?.status??"yet_to_do");const [urls,setUrls]=useState(todo?.attachments.join("\n")??"");const [project,setProject]=useState(todo?.project_id??"none");
 return <Modal title={todo?"Edit todo":"New todo"} close={()=>{if(!a.busy)close();}}><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(async()=>{const value=await mutate<Todo>(todo?`/v1/todos/${todo.id}`:"/v1/todos",todo?"PATCH":"POST",{title,description:description||null,assigned_to:assigned.trim()||me.data?.id,status,attachments:lines(urls),project_id:project==="none"?null:project});saved(value);},"Todo saved");}}>
 <Input label="Title" required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/><Textarea label="Description" rows={3} value={description} onChange={e=>setDescription(e.target.value)}/><Input label="Assigned to" description="A current c: or si: id. Leave empty to assign to yourself." value={assigned} placeholder={me.data?.id??"c:ada or si:scout"} onChange={e=>setAssigned(e.target.value)}/><StatusSelect value={status} onChange={setStatus}/><Select label="Related project" value={project} onValueChange={setProject} options={[{value:"none",label:"No project"},...projects.items.map(p=>({value:p.id,label:p.name}))]}/><More query={projects}/><Textarea label="Attachment links" description="One HTTPS URL per line, up to 20." rows={2} value={urls} onChange={e=>setUrls(e.target.value)}/><Feedback action={a}/><div className={s.actions}><Button type="submit" disabled={a.busy}>{todo?"Save changes":"Create todo"}</Button><Button type="button" variant="secondary" onClick={close} disabled={a.busy}>Cancel</Button></div>
 </form></Modal>;
}
export function Todos({initialData}:{initialData?:PageResult<Todo>}){
 const [view,setView]=useState("assigned_to_me"),[status,setStatus]=useState("all"),[assigned,setAssigned]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[creating,setCreating]=useState(false);const router=useRouter();
 const path="/v1/todos"+queryString({view,status:status==="all"?undefined:status,assigned_to:assigned||undefined,created_from:from?new Date(from).toISOString():undefined,created_to:to?new Date(to).toISOString():undefined,limit:50});
 const data=useList<Todo>(path,path==="/v1/todos?view=assigned_to_me&limit=50"?initialData:undefined);
 return <Page><PageHeader title="Todos" description="A clear next step, for you and the accounts you work with." actions={<Button onClick={()=>setCreating(true)}>New todo</Button>}/><div className={s.toolbar}><Select label="Work to show" value={view} onValueChange={setView} options={[{value:"assigned_to_me",label:"For me"},{value:"delegated_by_me",label:"Delegated by me"},{value:"all",label:"All accessible work"}]}/><StatusSelect value={status} onChange={setStatus} all/><Input label="Assignee" value={assigned} placeholder="Any c: or si: id" onChange={e=>setAssigned(e.target.value)}/><Input label="Created from" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input label="Created before" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><ResourceError error={data.error}/><Surface><div className={s.list}>{data.items.map(todo=><article className={s.item} key={todo.id}><div className={s.spread}><Link className={s.titleLink} href={`/todos/${todo.id}`}>{todo.title}</Link><Status value={todo.status}/></div>{todo.description?<p className={s.body}>{todo.description.slice(0,180)}</p>:null}<div className={s.meta}><Who actor={todo.assigned_to}/><span className={s.muted}>Updated {stamp(todo.updated_at)}</span></div></article>)}</div>{!data.items.length?<Empty>{data.isLoading?"Loading your work…":"No todos in this view. Create one or change the filters."}</Empty>:null}<More query={data}/></Surface>{creating?<TodoForm close={()=>setCreating(false)} saved={todo=>{setCreating(false);router.push(`/todos/${todo.id}`);}}/>:null}</Page>;
}
export function TodoDetail({id,initialData}:{id:string;initialData?:Todo}){
 const data=useResource<Todo>(`/v1/todos/${enc(id)}`,initialData);const [editing,setEditing]=useState(false);const a=useAction();const router=useRouter();const todo=data.data;
 return <Page width="reading"><PageHeader title={todo?.title??"Todo"} size="entity" back={{href:"/todos",label:"Todos"}} description={todo?`Updated ${stamp(todo.updated_at)}`:undefined} actions={<Button variant="secondary" onClick={()=>setEditing(true)} disabled={!todo}>Edit todo</Button>}/><ResourceError error={data.error}/>{todo?<><Surface><div className={s.spread}><Who actor={todo.assigned_to}/><Status value={todo.status}/></div><p className={s.body}>{todo.description||"No description yet."}</p><Attachments urls={todo.attachments}/><div className={s.meta}><span className={s.muted}>Assigned by</span><Who actor={todo.assigned_by}/>{todo.project_id?<Link className={s.rowLink} href={`/projects/${todo.project_id}`}>Related project →</Link>:null}</div><div className={s.toolbar}><StatusSelect value={todo.status} onChange={status=>void a.run(()=>mutate(`/v1/todos/${todo.id}`,"PATCH",{status}),"Status updated")}/><ConfirmMorph label="Delete todo" prompt="Delete this todo and its notes?" onConfirm={async()=>{await mutate(`/v1/todos/${todo.id}`,"DELETE");router.push("/todos");router.refresh();}}/></div><Feedback action={a}/></Surface><Notes id={todo.id}/><TodoSubscription todo={todo}/>{editing?<TodoForm todo={todo} close={()=>setEditing(false)} saved={()=>setEditing(false)}/>:null}</>:null}</Page>;
}
function Notes({id}:{id:string}){const data=useList<Note>(`/v1/todos/${enc(id)}/notes`);const [body,setBody]=useState("");const a=useAction();return <Section title="Notes" description="Keep context with the work."><Surface><form className={s.form} onSubmit={e=>{e.preventDefault();void a.run(async()=>{await mutate(`/v1/todos/${id}/notes`,"POST",{body});setBody("");},"Note added");}}><Textarea label="New note" required rows={3} value={body} onChange={e=>setBody(e.target.value)}/><Button type="submit" disabled={a.busy}>Add note</Button><Feedback action={a}/></form><ResourceError error={data.error}/>{data.items.map(note=><article className={s.item} key={note.id}><p className={s.body}>{note.body}</p><div className={s.meta}><Who actor={note.author}/><span className={s.muted}>{stamp(note.created_at)}</span></div></article>)}{!data.items.length?<Empty>No notes yet. Add the context someone needs to take the next step.</Empty>:null}<More query={data}/></Surface></Section>;}
