import {mkdirSync,readFileSync} from "node:fs";
import {expect,test} from "@playwright/test";
import {accountsSession,runAccounts,sessionOf,signIn,sameOrigin,BASE,ACCOUNTS} from "./support";

test("todos, shared projects, tasks, diary conflicts, history and notifications use the real service",async({browser})=>{
 test.setTimeout(180000);
 const context=await accountsSession(browser,"carbon",{reducedMotion:"reduce"});const page=await context.newPage();
 await signIn(page,runAccounts().carbon.email,"/todos");const me=(await sessionOf(context)).account!;
 const friendContext=await accountsSession(browser,"friend",{reducedMotion:"reduce"});const friend=await friendContext.newPage();await signIn(friend,runAccounts().friend.email,"/projects");const other=(await sessionOf(friendContext)).account!;
 await page.getByRole("button",{name:"New todo",exact:true}).click();let dialog=page.getByRole("dialog",{name:"New todo",exact:true});
 await dialog.getByLabel("Title",{exact:true}).fill("Prepare the handoff");await dialog.getByLabel("Description",{exact:true}).fill("Include the decisions and the next step.");await dialog.getByLabel("Assigned to",{exact:true}).fill(other.id);await dialog.getByRole("button",{name:"Create todo",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Prepare the handoff",exact:true})).toBeVisible();await expect(page).toHaveURL(/\/todos\/[0-9a-f-]+$/);const todoId=page.url().split("/").pop()!;
 await page.getByLabel("New note",{exact:true}).fill("Review the project diary before starting.");await page.getByRole("button",{name:"Add note",exact:true}).click();await expect(page.getByText("Review the project diary before starting.",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Edit todo",exact:true}).click();dialog=page.getByRole("dialog",{name:"Edit todo",exact:true});await dialog.getByLabel("Title",{exact:true}).fill("Prepare the final handoff");await dialog.getByRole("button",{name:"Save changes",exact:true}).click();await expect(page.getByRole("heading",{name:"Prepare the final handoff",exact:true})).toBeVisible();
 await friend.goto(`/todos/${todoId}`);await expect(friend.getByRole("heading",{name:"Prepare the final handoff",exact:true})).toBeVisible();
 await page.goto("/projects");await page.getByRole("button",{name:"New project",exact:true}).click();dialog=page.getByRole("dialog",{name:"New project",exact:true});await dialog.getByLabel("Project name",{exact:true}).fill("A thoughtful launch");await dialog.getByLabel("Description",{exact:true}).fill("Bring the release notes, decisions and final handoff together.");await dialog.getByLabel("Members",{exact:true}).fill(other.id);await dialog.getByLabel("Members",{exact:true}).press("Enter");await dialog.getByRole("switch",{name:"Private project"}).click();await dialog.getByLabel("Initial tasks",{exact:true}).fill("Draft release notes");await dialog.getByRole("button",{name:"Create project",exact:true}).click();await expect(page.getByRole("heading",{name:"A thoughtful launch",exact:true})).toBeVisible();await expect(page).toHaveURL(/\/projects\/[0-9a-f-]+$/);const projectId=page.url().split("/").pop()!;
 await page.getByRole("button",{name:"Claim task",exact:true}).click();await expect(page.getByText("Task claimed",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Add subtask",exact:true}).click();dialog=page.getByRole("dialog",{name:"New subtask",exact:true});await dialog.getByLabel("Task title",{exact:true}).fill("Confirm the acceptance checks");await dialog.getByLabel("Assigned to",{exact:true}).fill(other.id);await dialog.getByRole("button",{name:"Create task",exact:true}).click();await expect(page.getByRole("heading",{name:"Confirm the acceptance checks",exact:true})).toBeVisible();
 await friend.goto(`/projects/${projectId}`);await expect(friend.getByRole("heading",{name:"A thoughtful launch",exact:true})).toBeVisible();
 await page.getByRole("tab",{name:"Diary",exact:true}).click();await page.getByRole("button",{name:"Edit diary",exact:true}).click();await page.getByLabel("Diary Markdown",{exact:true}).fill("# Decisions\n\nKeep the handoff concise and useful.");await page.getByRole("button",{name:"Save diary",exact:true}).click();await expect(page.getByText("Diary saved",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Edit diary",exact:true}).click();await page.getByLabel("Diary Markdown",{exact:true}).fill("My preserved draft after a concurrent update.");
 const current=await (await friend.request.get(`/api/v1/projects/${projectId}/diary`)).json();const newer=await friend.request.put(`/api/v1/projects/${projectId}/diary`,{headers:{...sameOrigin(),"If-Match":`"${current.version}"`,"Idempotency-Key":crypto.randomUUID()},data:{markdown:"The collaborator saved the latest decision."}});expect(newer.ok(),await newer.text()).toBeTruthy();
 await page.getByRole("button",{name:"Save diary",exact:true}).click();await expect(page.getByRole("alert").first()).toBeVisible();await expect(page.getByLabel("Diary Markdown",{exact:true})).toHaveValue("My preserved draft after a concurrent update.");await page.getByRole("button",{name:"Cancel edit",exact:true}).click();await page.reload();await page.getByRole("tab",{name:"Diary",exact:true}).click();await expect(page.getByText("The collaborator saved the latest decision.",{exact:true})).toBeVisible();
 await page.getByRole("tab",{name:"Updates",exact:true}).click();await page.getByRole("button",{name:"Add blocker",exact:true}).click();dialog=page.getByRole("dialog",{name:"Add blocker",exact:true});await dialog.getByLabel("Entry title",{exact:true}).fill("Waiting for review");await dialog.getByLabel("Entry description",{exact:true}).fill("The final checks need a second pair of eyes.");await dialog.getByRole("button",{name:"Add blocker",exact:true}).click();await expect(page.getByRole("heading",{name:"Waiting for review",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Post update",exact:true}).click();dialog=page.getByRole("dialog",{name:"Post update",exact:true});await dialog.getByLabel("Entry title",{exact:true}).fill("Ready for the final review");await dialog.getByLabel("Entry description",{exact:true}).fill("Every acceptance check is now recorded.");await dialog.getByRole("button",{name:"Post update",exact:true}).click();await expect(page.getByRole("heading",{name:"Ready for the final review",exact:true})).toBeVisible();
 await page.getByRole("tab",{name:"History",exact:true}).click();await page.getByRole("button",{name:"View snapshot",exact:true}).first().click();await expect(page.getByRole("dialog",{name:"Project snapshot",exact:true})).toContainText("A thoughtful launch");await page.getByRole("button",{name:"Close dialog",exact:true}).click();
 mkdirSync("screens",{recursive:true});
 for(const theme of ["light","dark"] as const)for(const mobile of [false,true]){
  await page.emulateMedia({colorScheme:theme,reducedMotion:"reduce"});await page.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:900});
  await page.getByRole("tab",{name:"Tasks",exact:true}).click();await expect(page.getByRole("heading",{name:"Draft release notes",exact:true})).toBeVisible();await page.screenshot({path:`screens/project-${theme}-${mobile?"phone":"desktop"}.png`,fullPage:true});
  await page.goto(`/todos/${todoId}`);await expect(page.getByRole("heading",{name:"Prepare the final handoff",exact:true})).toBeVisible();await page.screenshot({path:`screens/todo-${theme}-${mobile?"phone":"desktop"}.png`,fullPage:true});await page.goto(`/projects/${projectId}`);
 }
 await page.setViewportSize({width:1440,height:900});await page.getByRole("button",{name:"Edit project",exact:true}).click();dialog=page.getByRole("dialog",{name:"Edit project",exact:true});await dialog.getByRole("button",{name:`Remove ${other.id}`,exact:true}).click();await dialog.getByRole("button",{name:"Save project",exact:true}).click();await expect(dialog).not.toBeVisible();const denied=await friend.request.get(`/api/v1/projects/${projectId}`);expect(denied.status()).toBe(404);
 await page.goto("/notifications");await page.getByRole("switch",{name:"Project updates",exact:true}).click();await page.getByRole("button",{name:"Save email settings",exact:true}).click();await expect(page.getByText("Email settings saved",{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole("switch",{name:"Project updates",exact:true})).toBeChecked();
 await page.goto(`/projects/${projectId}`);await page.getByRole("tab",{name:"Updates",exact:true}).click();await page.getByRole("button",{name:"Complete project",exact:true}).click();dialog=page.getByRole("dialog",{name:"Complete project",exact:true});await dialog.getByLabel("Entry title",{exact:true}).fill("Handoff complete");await dialog.getByLabel("Entry description",{exact:true}).fill("The work and decisions are ready for the next step.");await dialog.getByRole("button",{name:"Complete project",exact:true}).click();await dialog.getByRole("button",{name:"Confirm",exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole("heading",{name:"Handoff complete",exact:true})).toBeVisible();
 const before=await page.request.post("/api/v1/todos",{headers:{Origin:"https://other.example","Idempotency-Key":crypto.randomUUID()},data:{title:"CSRF",assigned_to:me.id}});expect(before.status()).toBe(403);
 expect(new URL(page.url()).origin).toBe(BASE);await context.close();await friendContext.close();
});


test("a custodian manages a real Silicon allow-list and notification subscriptions",async({browser})=>{
 const context=await accountsSession(browser,"carbon",{reducedMotion:"reduce"});const page=await context.newPage();await signIn(page,runAccounts().carbon.email,"/silicons");
 const created=await context.request.post(`${ACCOUNTS}/v1/me/silicons`,{headers:{Origin:ACCOUNTS,"Idempotency-Key":crypto.randomUUID()},data:{id:`si:commit-browser-${Date.now()}`,display_name:"Release assistant"}});expect(created.status()).toBe(201);const identity=await created.json();const silicon=identity.silicon;
 const stack=JSON.parse(readFileSync(process.env.TEST_STACK_JSON!,"utf8"));
 const first=await fetch(`${stack.accounts_api_url}/v1/silicons/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:silicon.id,stk:identity.stk})});expect(first.status).toBe(200);const firstToken=(await first.json()).access_token;
 const short=await fetch(`${stack.accounts_api_url}/v1/me/short-lived-tokens`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${firstToken}`},body:JSON.stringify({app_id:"commit"})});expect(short.status).toBe(201);const slt=(await short.json()).slt;
 const exchanged=await fetch(`${stack.accounts_api_url}/v1/oauth/token`,{method:"POST",headers:{authorization:`Basic ${Buffer.from(`commit:${stack.apps.commit.app_secret}`).toString("base64")}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:silicon:params:oauth:grant-type:slt",slt})});expect(exchanged.status).toBe(200);const token=(await exchanged.json()).access_token;
 const admitted=await fetch("http://127.0.0.1:4141/api/v1/me",{headers:{authorization:`Bearer ${token}`}});expect(admitted.status).toBe(200);
 await page.reload();await page.getByLabel("Account to allow",{exact:true}).fill(runAccounts().friend.id);await page.getByRole("button",{name:"Allow account",exact:true}).click();await expect(page.getByText("Account allowed",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:`Remove ${runAccounts().friend.id}`,exact:true})).toBeVisible();await page.screenshot({path:"screens/silicon-allowlist.png",fullPage:true});
 await page.goto("/notifications");await page.getByLabel("Webhook URL",{exact:true}).fill("https://example.com/commit-events");await page.getByRole("combobox",{name:"Events to deliver",exact:true}).click();await page.getByRole("option",{name:"Every update",exact:true}).click();await page.getByRole("button",{name:"Save Silicon settings",exact:true}).click();await expect(page.getByText("Silicon notification settings saved",{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel("Webhook URL",{exact:true})).toHaveValue("https://example.com/commit-events");await page.screenshot({path:"screens/silicon-notifications.png",fullPage:true});
 await page.getByLabel("Webhook URL",{exact:true}).fill("");await page.getByRole("button",{name:"Save Silicon settings",exact:true}).click();await expect(page.getByText("Silicon notification settings saved",{exact:true})).toBeVisible();
 const delegated=await fetch("http://127.0.0.1:4141/api/v1/todos",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({title:"Review the release plan",assigned_to:runAccounts().carbon.id})});expect(delegated.status).toBe(201);const todo=await delegated.json();await page.goto(`/todos/${todo.id}`);

 await page.getByRole("combobox",{name:"Events to deliver",exact:true}).click();await page.getByRole("option",{name:"Status changes",exact:true}).click();await page.getByRole("button",{name:"Save todo subscription",exact:true}).click();await expect(page.getByText("Todo subscription saved",{exact:true})).toBeVisible();
 await page.goto("/silicons");await page.getByRole("button",{name:`Remove ${runAccounts().friend.id}`,exact:true}).click();await page.getByRole("button",{name:"Delete",exact:true}).click();await expect(page.getByText("Account removed",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:`Remove ${runAccounts().friend.id}`,exact:true})).toHaveCount(0);
 // Leave no external destination active after verification.
 await page.goto("/notifications");await page.getByLabel("Webhook URL",{exact:true}).fill("");await page.getByRole("combobox",{name:"Events to deliver",exact:true}).click();await page.getByRole("option",{name:"No subscription",exact:true}).click();await page.getByRole("button",{name:"Save Silicon settings",exact:true}).click();await expect(page.getByText("Silicon notification settings saved",{exact:true})).toBeVisible();
 await context.close();
});
